### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by Amit12690** [KAIST-VCLAB/DeepFormableTag#2]
Is the training code going to be released anytime soon ? It would be amazing to try the training end to end.

**Comment by myaldiz** [comment]
Dear @Amit12690,

We refactored and implemented many parts of the code from scratch and currently working on it to finish the training code as well. I won't be able to give specific timeline at this point, but we will provide a flexible training environment that can easily be applied to many different conditions. And hopefully even better models.
I apologize for the delay, I will be tagging you once we release it.
Thank you for your interest again.

**Comment by myaldiz** [comment]
Things to include/fix for training release:
- [x] #5

**Comment by myaldiz** [comment]
We have released the training code, you can now refer to the original implementation!
