### ISSUE TITLE
Running deepformable_tutorial.ipynb with a different test image

### ISSUE THREAD

**Issue by Amit12690** [KAIST-VCLAB/DeepFormableTag#3]
I am trying to run deepformable_tutorial.ipynb  with a different image  ( test-realworld/deformation_2cm/1_2/GO5A5632.png  attached below).  
However I am not getting any detections.  Is there any other change I need to make in order to run the detector on different images ?  

![GO5A5632](https://user-images.githubusercontent.com/4231878/155145817-9edf672a-b12e-4180-834e-fb739989dbe7.png)

**Comment by myaldiz** [comment]
We have a parameter called `cfg.TEST.NMS_SCORE_CRITERIA` which is by default set to `“mc_obj_bs_product”`.
This parameter scores the confidence of the prediction by the product of message prediction confidence, objectness, and bit similarity to the provided binary messages in a json formatted *config file*. 
In the jupyter notebook, it uses the below *config file*:
```py
marker_config_path = deepformable_root / “files/template_config.json”
```
However, the test dataset supposed to use `test-realworld/marker-config.json` instead.
As you provide wrong binary messages for matching to calculate the confidence score, the scores are below the threshold parameter `cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST` and they are discarded.
I just pushed some more comments on jupyter notebook and here is what I get from the predictions when the correct marker config file is provided:
![image](https://user-images.githubusercontent.com/11998186/155161738-9ef7c5d9-4b19-4ab1-88f6-074711983174.png)
Thank you for your interest!

**Comment by Amit12690** [comment]
Thanks a lot. It works ! 
Is there any way to run it on the sample video ?

**Comment by myaldiz** [comment]
You can use [flexible reader](https://github.com/KAIST-VCLAB/DeepFormableTag/blob/b765f379369ba5aa82fb21a727a63255e2920129/deepformable/utils/general_utils.py#L8) to load the videos iteratively, or use [detection demo](https://github.com/KAIST-VCLAB/DeepFormableTag/tree/b765f379369ba5aa82fb21a727a63255e2920129#detection-demo).

I guess there is a way to [show videos in jupyter notebook](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Video), share with us if you make it work properly :)

**Comment by Amit12690** [comment]
Thanks a lot . I was able to generate the video output in colab using :  

> !python /content/deepformable/tools/predictor_demo.py --video-input /content/deepformable/files/example_video_001.mov --output test_out.mp4 --parallel --config-file /content/deepformable/configs/deepformable-main.yaml --marker-config-file /content/deepformable/files/template_config.json --opts MODEL.WEIGHTS /content/deepformable/models/deepformable_model.pth

**Comment by myaldiz** [comment]
Yeah that is an express solution 👍
