### ISSUE TITLE
Accessing the detector and decoder modules of the model

### ISSUE THREAD

**Issue by Amit12690** [KAIST-VCLAB/DeepFormableTag#6]
Is there anyway to access the decoder  ,  detector  modules fro fprop  like we access the generator using  `model.marker_generator` ?

**Comment by myaldiz** [comment]
Yes, you can. We inherit from [GeneralizedRCNN](https://github.com/facebookresearch/detectron2/blob/main/detectron2/modeling/meta_arch/rcnn.py), please check its source code to see the variables you can access.

**Comment by Amit12690** [comment]
Thanks @myaldiz
