### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by yeong-dev** [KAIST-VCLAB/DeepFormableTag#8]
Hello, I got impressed by your brilliant work.
By the way, here's my question:
How long does it take for training?
I want to know about training hours.

Thanks.

**Comment by myaldiz** [comment]
Hi @yeong5366, thank you for the kind words.
We used 8 Nvidia GPUs (Titan RTX) 24GB memory with batch size of 16 (2 images per GPU).
With this configuration the training takes around ~8 hours.

**Comment by yeong-dev** [comment]
Wow! Thanks for your fast reply.
This work looks great! I believe this would be applied in many ways.
Have a nice day! :)
